# Generated by Django 3.2.8 on 2022-06-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', multiselectfield.db.fields.MultiSelectField(choices=[('au', 'Australia'), ('ca', 'Canada'), ('cn', 'China'), ('eg', 'Egypt'), ('fr', 'France'), ('in', 'India'), ('it', 'Italy'), ('mx', 'Mexico'), ('nz', 'New Zealand'), ('ru', 'Russia'), ('uk', 'UK'), ('us', 'USA')], max_length=35)),
                ('source', multiselectfield.db.fields.MultiSelectField(choices=[('bbc-news', 'BBC'), ('abc-news', 'ABC'), ('al-jazeera-english', 'AL-Jazeera'), ('marca', 'Marca'), ('cnn', 'CNN'), ('reuters', 'Reuters')], max_length=54)),
                ('keyword', multiselectfield.db.fields.MultiSelectField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
