# Generated by Django 3.2.8 on 2022-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='keyword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
