# Generated by Django 3.2.8 on 2022-06-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_setting_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='country',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='source',
        ),
    ]
