# Generated by Django 3.2.8 on 2022-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220622_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=40)),
            ],
        ),
    ]
